config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :bookings, only: [:new, :show, :create]

  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: "Flight"
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"

  scope :available_flights, lambda { |departure:, arrival:, date_picked:|
    where(departure_airport_id: departure,
          arrival_airport_id: arrival,
          date: (date_picked.midnight..date_picked.midnight + 1.day))
  }

  def formatted_date
    date.strftime("%d/%m/%Y")
  end

  def departure_time
    date.strftime("%H:%M")
  end

  def arrival_time
    arrival_date = date + duration
    arrival_date.strftime("%H:%M")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  # validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
  end

  def new
    @booking = Booking.new
    @num_passengers = params[:num_passengers].to_i
    @flight = Flight.find(params[:flight_id])

    @num_passengers.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking
      flash[:success] = "Your booking has been registered, have a nice trip!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [a.codename, a.id] }
    @date_options = Flight.all
                          .order(:date)
                          .map { |f| [f.formatted_date, f.date] }
                          .uniq(&:first)
    @available_flights = []
    @num_passengers = params[:num_passengers]

    if params[:commit].present?
      @available_flights = Flight.available_flights(departure: params[:departure_airport_id],
                                                    arrival: params[:arrival_airport_id],
                                                    date_picked: params[:date].to_date)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_with model: @booking do |f| %>
    <div>
        <%= f.label :flight_id %>
        <%= f.number_field :flight_id, value: @flight.id ,readonly: true %>
        <%= f.label :departure_airport %>
        <%= f.text_field :departure_airport, value: @flight.departure_airport.codename ,disabled: true %>
        <%= f.label :arrival_airport %>
        <%= f.text_field :arrival_airport, value: @flight.arrival_airport.codename ,disabled: true %>
    </div>

    <div>
        <%= f.label :date %>
        <%= f.date_field :date, value: @flight.date.to_date, disabled: true %>
        <%= f.label :departure_time %>
        <%= f.time_field :time, value: @flight.departure_time, disabled: true  %>
    </div>

    <%= f.fields_for :passengers do |passengers_form| %>
        <h3>Passenger <%= passengers_form.index + 1 %></h3>
        <div>
            <%= passengers_form.label :name %>
            <%= passengers_form.text_field :name %>
        </div>

        <div>
            <%= passengers_form.label :email %>
            <%= passengers_form.email_field :email %>
        </div>
    <% end %>

    <%= f.submit "Buy Tickets" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Your Booking</h1>

<h2>Flight Information</h2>

<ul>
    <li><strong>ID: </strong><%= @flight.id %></li>
    <li><strong>Departure Airport: </strong><%= @flight.departure_airport.codename %></li>
    <li><strong>Arrival Airport: </strong><%= @flight.arrival_airport.codename %></li>
    <li><strong>Departure Time: </strong><%= @flight.departure_time %></li>
    <li><strong>Arrival Time: </strong><%= @flight.arrival_time %></li>
</ul>

<h2>Passenger Information</h2>

<% @booking.passengers.each_with_index do |passenger, index| %>
    <h3>Passenger <%= index + 1 %></h3>
    <ul>
        <li><strong>Name: </strong><%= passenger.name %></li>
        <li><strong>Email: </strong><%= passenger.email %></li>
    </ul>
<% end %>

app/views/flights/index.html.erb
<h1>Flights Booker</h1>

<%= form_with url: flights_path, method: :get do |f| %>
    <div>
        <%= f.label :departure_airport %>
        <%= f.select(:departure_airport_id, @airport_options)%>
    </div>

    <div>
        <%= f.label :arrival_airport %>
        <%= f.select(:arrival_airport_id, @airport_options)%>
    </div>

    <div>
        <%= f.label :passengers %>
        <%= f.select(:num_passengers, [*1..4])%>
    </div>

      
    <div>
        <%= f.label :date %>
        <%= select_tag(:date, options_for_select(@date_options)) %>
    </div>


    <%= f.submit "Search" %>
<% end %>

<h2>Available Flights</h2>

<% if @available_flights.any? %>

    <%= form_with url: new_booking_path, method: :get do |f| %>
        <%= f.hidden_field :num_passengers, value: @num_passengers %>
        <%= f.collection_radio_buttons :flight_id, @available_flights, :id, :departure_time %>
        <%= f.submit "Book a passage"%>
    <% end %>

<% else %>
    <p>There are no available flights </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <h1><%= link_to "Flight Booker", root_path %></h1>
    </nav>

    <% if flash.any? %>
      <% flash.each do |_type, message| %>
        <p><%= message %></p>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>